services:
  app:
    build: .
    image: demoapp
#    container_name: app
#    ports:
#      - "3000:3000"
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: none
  nginx:
    image: nginx:1.25.5-alpine
#    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
